const ICON_DATA = [
    "Achatina.png",
    "Acrocanthosaurus.png",
    "Allosaurus.png",
    "Amargasaurus.png",
    "Ammonite.png",
    "Andrewsarchus.png",
    "Anglerfish.png",
    "Ankylosaurus.png",
    "Archaeopteryx.webp",
    "Archelon-Entry-Icon_ASA.webp",
    "Argentavis.png",
    "Arthropluera.png",
    "Astrocetus.png",
    "Astrodelphis.png",
    "Aureliax.webp",
    "Baryonyx.webp",
    "Basilisk.png",
    "Basilosaurus.png",
    "Beelzebufo.png",
    "Bison.webp",
    "Bloodstalker.png",
    "Brontosaurus.png",
    "Bulbdog.png",
    "Carbonemys.webp",
    "Carcharodontosaurus.png",
    "Carnotaurus.png",
    "Cat.webp",
    "Ceratosaurus.png",
    "Chalicotherium.png",
    "Cnidaria.png",
    "Compy.png",
    "DAEDON.png",
    "Deathworm.png",
    "Deinonychus.png",
    "Deinosuchus.png",
    "Deinotherium_Icon_ASA.webp",
    "Desmodus.png",
    "Dilophosaur.png",
    "Dimetrodon.png",
    "Dimorphodon.png",
    "Dinopithecus.png",
    "Diplocaulus.png",
    "Diplodocus.png",
    "Dire_Bear.webp",
    "Direwolf.png",
    "Dodo.png",
    "Doedicurus.png",
    "Drakeling.avif",
    "Dreadmare_Icon.avif",
    "Dreadnoughtus_Icon.avif",
    "Dung_Beetle.webp",
    "Dunkleosteus.png",
    "Electrophorus.png",
    "Empty_Elderclaw.webp",
    "Empty_Gigadesmodus.webp",
    "Empty_Parrot_Icon.png",
    "Empty_Umbra_Icon.png",
    "Empty_tidepup.png",
    "Equus.png",
    "Eurypterid.png",
    "Fasolasuchus.png",
    "FasolasuchusHead_Icon.avif",
    "Featherlight.png",
    "Fenrir.png",
    "Ferox.png",
    "Ferox_(Large).png",
    "Fjordhawk.png",
    "Gacha.png",
    "Gallimimus.png",
    "Gasbags.png",
    "Giant_Beaver.png",
    "Giant_Bee.png",
    "Giganotosaurus.png",
    "Gigantopithecus.png",
    "Gigantoraptor.png",
    "Gloon.png",
    "Glowbug.png",
    "Glowtail.png",
    "Griffin.webp",
    "Hesperornis.png",
    "Hyaenodon.png",
    "Ichthyornis.png",
    "Ichthyosaurus.png",
    "Iguanodon.png",
    "Jerboa.png",
    "Jug_Bug.png",
    "Kairuku.png",
    "Kaprosuchus.png",
    "Karkinos.png",
    "Kentrosaurus.png",
    "Lamprey.png",
    "Leedsichthys.png",
    "Liopleurodon.png",
    "Lymantria.png",
    "Lystrosaurus.png",
    "Maewing.png",
    "Magmasaur.png",
    "Mammoth.png",
    "Managarmr.webp",
    "Manta.png",
    "Mantis.png",
    "Megachelon.png",
    "Megalania.webp",
    "Megaloceros.png",
    "Megalodon.png",
    "Megalosaurus.png",
    "Meganeura.png",
    "Megaraptor.avif",
    "Megatherium.png",
    "Mesopithecus.png",
    "Microraptor.png",
    "Morellatops.png",
    "Mosasaurus.png",
    "Moschops.png",
    "Nameless.png",
    "Noglin.png",
    "Oasisaur.png",
    "Onyc.png",
    "Otter.png",
    "Oviraptor.png",
    "Ovis.png",
    "Pachy.png",
    "Pachyrhinosaurus.png",
    "Paleoctopus_Icon.png",
    "Paraceratherium.webp",
    "Parasaur.png",
    "Pegomastax.png",
    "Pelagornis.png",
    "Phiomia.webp",
    "Phoenix.png",
    "Plesiosaur.png",
    "Procoptodon.png",
    "Pteranodon.png",
    "Purlovia.png",
    "Pyromane.png",
    "Quetzal.png",
    "Raptor.png",
    "Ravager.png",
    "Reaper.png",
    "Rex.png",
    "Rock_Drake.webp",
    "Rock_Elemental.png",
    "Roll_Rat.png",
    "Sabertooth.png",
    "Sarco.png",
    "Scorpion.png",
    "Shadowmane.png",
    "Shastasaurus.png",
    "Shinehorn.png",
    "Sinomacrops.png",
    "Snow_Owl.png",
    "Solwyn.avif",
    "Spider.png",
    "Spino.png",
    "Stegosaurus.png",
    "Tapejara.png",
    "Tek_Stryder.png",
    "Terror_Bird.png",
    "Therizinosaur.webp",
    "Thorny_Dragon.png",
    "Thylacoleo.webp",
    "Titanoboa.png",
    "Titanosaur.png",
    "Trike.png",
    "Trilobite.png",
    "Troodon.png",
    "Tropeognathus.png",
    "Tusoteuthis.webp",
    "VEILWYN.avif",
    "Velonasaur.webp",
    "Voidwyrm.png",
    "Vulture.png",
    "Woolly_Rhinoceros.png",
    "Wyvern.png",
    "Xiphactinus.png",
    "YiLing.avif",
    "Yuthyrannus.avif",
    "malwyn.avif",
    "ossidon.avif"
];

const DINO_REGISTRY = {
                    "ACHATINA": { base: 500, variants: { "ABERRANT": 700 }, img: "Achatina.png" },
                    "ACROCANTHOSAURUS": { base: 2800, variants: { "S": 3800, "X": 3200 }, img: "Acrocanthosaurus.png" },
                    "ALLOSAURUS": { base: 1800, variants: { "R": 2000, "S": 2300, "X": 2000 }, img: "Allosaurus.png" },
                    "AMARGASAURUS": { base: 3000, img: "Amargasaurus.png" },
                    "ANDREWSARCHUS": { base: 1800, variants: { "S": 2800 }, img: "Andrewsarchus.png" },
                    "ANGLERFISH": { base: 1100, variants: { "ABERRANT": 1300 }, img: "Anglerfish.png" },
                    "ANKYLOSAURUS": { base: 500, variants: { "ABERRANT": 700, "S": 1000, "X": 700 }, img: "Ankylosaurus.png" },
                    "ARANEO": { base: 600, variants: { "ABERRANT": 800, "S": 1100 }, img: "Spider.png" },
                    "ARCHAEOPTERYX": { base: 900, img: "Archaeopteryx.webp" },
                    "ARCHELON": { base: 1800, variants: { "X": 2000 }, img: "Archelon-Entry-Icon_ASA.webp" },
                    "ARGENTAVIS": { base: 600, variants: { "S": 1100, "X": 800 }, img: "Argentavis.png" },
                    "ARMADOGGO": { variants: { "(DLC)": 1700 } },
                    "ARTHROPLUERA": { base: 1300, variants: { "ABERRANT": 1500 }, img: "Arthropluera.png" },
                    "ASTROCETUS": { base: 9000, img: "Astrocetus.png" },
                    "ASTRODELPHIS": { base: 7000, img: "Astrodelphis.png" },
                    "AURELIAX": { variants: { "(DLC)": 4000 }, img: "Aureliax.webp" },
                    "BARYONYX": { base: 1100, variants: { "ABERRANT": 1300 }, img: "Baryonyx.webp" },
                    "BASILISK": { base: 3000, img: "Basilisk.png" },
                    "BASILOSAURUS": { base: 2500, variants: { "S": 3000, "X": 2700 }, img: "Basilosaurus.png" },
                    "BEELZEBUFO": { base: 800, variants: { "ABERRANT": 1000 }, img: "Beelzebufo.png" },
                    "BISON": { base: 2200, img: "Bison.webp" },
                    "BLOODSTALKER": { base: 2100, img: "Bloodstalker.png" },
                    "BRONTOSAURUS": { base: 2300, variants: { "R": 2500 }, img: "Brontosaurus.png" },
                    "BULBDOG": { base: 600, img: "Bulbdog.png" },
                    "BURROWBUCK": { variants: { "(DLC)": 5000 } },
                    "CARBONEMYS": { base: 500, variants: { "ABERRANT": 600, "R": 600 }, img: "Carbonemys.webp" },
                    "CARCHARODONTOSAURUS": { base: 5000, variants: { "S": 6000 }, img: "Carcharodontosaurus.png" },
                    "CARNOTAURUS": { base: 1600, variants: { "ABERRANT": 1800 }, img: "Carnotaurus.png" },
                    "CASTOROIDES": { base: 600, variants: { "S": 1100 }, img: "Giant_Beaver.png" },
                    "CAT": { base: 800, variants: { "S": 1300 }, img: "Cat.webp" },
                    "CERATOSAURUS": { base: 2000, variants: { "S": 3000 }, img: "Ceratosaurus.png" },
                    "CHALICOTHERIUM": { base: 1500, img: "Chalicotherium.png" },
                    "COMPY": { base: 500, img: "Compy.png" },
                    "COSMO": { variants: { "(DLC)": 1200 } },
                    "CRYOLOPHOSAURUS": { base: 2700, variants: { "X": 3000 } },
                    "DAEODON": { base: 1700, variants: { "R": 1900, "S": 3700 }, img: "DAEDON.png" },
                    "DEINONYCHUS": { base: 2000, variants: { "S": 3000 }, img: "Deinonychus.png" },
                    "DEINOSUCHUS": { base: 2200, variants: { "S": 3200, "X": 2700 }, img: "Deinosuchus.png" },
                    "DEINOTHERIUM": { base: 2800, img: "Deinotherium_Icon_ASA.webp" },
                    "DESMODUS": { base: 1600, variants: { "S": 2600 }, img: "Desmodus.png" },
                    "DILOPHOSAUR": { base: 500, variants: { "R": 700 }, img: "Dilophosaur.png" },
                    "DIMETRODON": { base: 1000, variants: { "ABERRANT": 1200 }, img: "Dimetrodon.png" },
                    "DIMORPHODON": { base: 500, variants: { "ABERRANT": 700 }, img: "Dimorphodon.png" },
                    "DINOPITHECUS": { base: 1500, img: "Dinopithecus.png" },
                    "DIPLOCAULUS": { base: 900, variants: { "ABERRANT": 1100 }, img: "Diplocaulus.png" },
                    "DIPLODOCUS": { base: 1800, variants: { "ABERRANT": 2000 }, img: "Diplodocus.png" },
                    "DIRE BEAR": { base: 1000, variants: { "ABERRANT": 1200, "S": 1500 }, img: "Dire_Bear.webp" },
                    "DIREWOLF": { base: 1100, variants: { "R": 1300, "S": 2100 }, img: "Direwolf.png" },
                    "DODO": { base: 200, variants: { "ABERRANT": 400, "ZOMBIE": 500 }, img: "Dodo.png" },
                    "DOEDICURUS": { base: 500, variants: { "ABERRANT": 700, "S": 1000 }, img: "Doedicurus.png" },
                    "DRAKELING": { variants: { "(DLC)": 2000 }, img: "Drakeling.avif" },
                    "DREADMARE": { variants: { "(DLC)": 5000 }, img: "Dreadmare_Icon.avif" },
                    "DREADNOUGHTUS": { base: 6500, img: "Dreadnoughtus_Icon.avif" },
                    "DUNG BEETLE": { base: 300, variants: { "ABERRANT": 500 }, img: "Dung_Beetle.webp" },
                    "DUNKLEOSTEUS": { base: 2000, variants: { "S": 3000, "X": 2200 }, img: "Dunkleosteus.png" },
                    "ELDERCLAW": { variants: { "(DLC)": 5000 }, img: "Empty_Elderclaw.webp" },
                    "ELECTROPHORUS": { base: 1500, variants: { "ABERRANT": 1700 }, img: "Electrophorus.png" },
                    "ENFORCER": { base: 3000 },
                    "EQUUS": { base: 1200, variants: { "ABERRANT": 1400, "R": 1400 }, img: "Equus.png" },
                    "FASOLASUCHUS": { base: 4000, variants: { "ABERRANT": 5000, "S": 8000 }, img: "Fasolasuchus.png" },
                    "FEATHERLIGHT": { base: 700, img: "Featherlight.png" },
                    "FENRIR": { base: 3500, variants: { "S": 1800 }, img: "Fenrir.png" },
                    "FEROX": { base: 1900, img: "Ferox.png" },
                    "FJORDHAWK": { base: 1100, img: "Fjordhawk.png" },
                    "GACHA": { base: 1000, img: "Gacha.png" },
                    "GALLIMIMUS": { base: 1000, img: "Gallimimus.png" },
                    "GASBAGS": { base: 1300, variants: { "R": 1500 }, img: "Gasbags.png" },
                    "GIANT BEE": { base: 500, img: "Giant_Bee.png" },
                    "GIGADESMODUS": { variants: { "(DLC)": 7000 }, img: "Empty_Gigadesmodus.webp" },
                    "GIGANOTOSAURUS": { base: 4000, variants: { "R": 4500, "TEK": 6000 }, img: "Giganotosaurus.png" },
                    "GIGANTOPITHECUS": { base: 1200, variants: { "ABERRANT": 1400 }, img: "Gigantopithecus.png" },
                    "GIGANTORAPTOR": { base: 5000, variants: { "ABERRANT": 6000 }, img: "Gigantoraptor.png" },
                    "GLOON": { variants: { "(DLC)": 2000 }, img: "Gloon.png" },
                    "GLOWTAIL": { base: 600, img: "Glowtail.png" },
                    "GOLEM (ELEMENTAL)": { variants: { "CHALK": 3000, "ICE": 3000, "ROCK": 2500, "X": 3000 }, img: "Rock_Elemental.png" },
                    "GRAND TORTUGAR": { base: 1600 },
                    "GRIFFIN": { base: 1900, variants: { "S": 2900 }, img: "Griffin.webp" },
                    "HELICOPRION": { base: 3000, variants: { "S": 3700, "X": 3300 } },
                    "HESPERORNIS": { base: 2000, img: "Hesperornis.png" },
                    "HYAENODON": { base: 1400, img: "Hyaenodon.png" },
                    "ICHTHYORNIS": { base: 800, img: "Ichthyornis.png" },
                    "ICHTHYOSAURUS": { base: 1100, variants: { "X": 1300 }, img: "Ichthyosaurus.png" },
                    "IGUANODON": { base: 1200, variants: { "ABERRANT": 1400 }, img: "Iguanodon.png" },
                    "JERBOA": { base: 500, img: "Jerboa.png" },
                    "KAIRUKU": { base: 900, img: "Kairuku.png" },
                    "KAPROSUCHUS": { base: 1300, img: "Kaprosuchus.png" },
                    "KARKINOS": { base: 4200, img: "Karkinos.png" },
                    "KENTROSAURUS": { base: 1200, img: "Kentrosaurus.png" },
                    "LIOPLEURODON": { base: 2000, img: "Liopleurodon.png" },
                    "LUMIA": { variants: { "(DLC)": 7000 } },
                    "LYMANTRIA": { base: 1000, img: "Lymantria.png" },
                    "LYSTROSAURUS": { base: 700, variants: { "ABERRANT": 900 }, img: "Lystrosaurus.png" },
                    "MAEGUANA": { base: 900, variants: { "S": 1400 } },
                    "MAEWING": { base: 900, variants: { "S": 1400 }, img: "Maewing.png" },
                    "MAGMASAUR": { base: 3400, variants: { "S": 4400 }, img: "Magmasaur.png" },
                    "MALWYN": { variants: { "(DLC)": 2500 }, img: "malwyn.avif" },
                    "MAMMOTH": { base: 1200, img: "Mammoth.png" },
                    "MANAGARMR": { base: 3300, variants: { "S": 4300 }, img: "Managarmr.webp" },
                    "MANTA": { base: 1400, variants: { "ABERRANT": 1600 }, img: "Manta.png" },
                    "MANTIS": { base: 1900, variants: { "S": 2900 }, img: "Mantis.png" },
                    "MEGACHELON": { base: 6000, img: "Megachelon.png" },
                    "MEGALANIA": { base: 1100, variants: { "ABERRANT": 1400 }, img: "Megalania.webp" },
                    "MEGALOCEROS": { base: 1300, img: "Megaloceros.png" },
                    "MEGALODON": { base: 1700, variants: { "S": 2700, "X": 1800 }, img: "Megalodon.png" },
                    "MEGALOSAURUS": { base: 2000, variants: { "ABERRANT": 2200, "S": 4000 }, img: "Megalosaurus.png" },
                    "MEGARAPTOR": { base: 2700, variants: { "S": 4700 }, img: "Megaraptor.avif" },
                    "MEGATHERIUM": { base: 1800, variants: { "R": 2000 }, img: "Megatherium.png" },
                    "MESOPITHECUS": { base: 700, img: "Mesopithecus.png" },
                    "MICRORAPTOR": { base: 800, img: "Microraptor.png" },
                    "MORELLATOPS": { base: 1100, img: "Morellatops.png" },
                    "MOSASAURUS": { base: 3700, variants: { "S": 4200, "X": 3900 }, img: "Mosasaurus.png" },
                    "MOSCHOPS": { base: 400, variants: { "ABERRANT": 600 }, img: "Moschops.png" },
                    "NOGLIN": { base: 8000, img: "Noglin.png" },
                    "ONYC": { base: 1500, img: "Onyc.png" },
                    "OSSIDON": { variants: { "(DLC)": 3000, "S": 5000 }, img: "ossidon.avif" },
                    "OTTER": { base: 700, variants: { "ABERRANT": 900, "S": 1200, "X": 900 }, img: "Otter.png" },
                    "OVIRAPTOR": { base: 500, img: "Oviraptor.png" },
                    "OVIS": { base: 600, variants: { "ABERRANT": 800 }, img: "Ovis.png" },
                    "PACHYRHINOSAURUS": { base: 1300, img: "Pachyrhinosaurus.png" },
                    "PALAEOCTOPUS": { base: 3000, img: "Paleoctopus_Icon.png" },
                    "PARACERATHERIUM": { base: 1300, variants: { "ABERRANT": 1500, "X": 1500 }, img: "Paraceratherium.webp" },
                    "PARASAUR": { base: 1000, variants: { "ABERRANT": 1200, "R": 1200, "TEK": 1200, "X": 1200 }, img: "Parasaur.png" },
                    "PARROT": { variants: { "(DLC)": 1000 }, img: "Empty_Parrot_Icon.png" },
                    "PEGOMASTAX": { base: 900, img: "Pegomastax.png" },
                    "PELAGORNIS": { base: 900, img: "Pelagornis.png" },
                    "PHIOMIA": { base: 700, img: "Phiomia.webp" },
                    "PHOENIX": { base: 9000, img: "Phoenix.png" },
                    "PLESIOSAUR": { base: 3700, variants: { "S": 4200 }, img: "Plesiosaur.png" },
                    "PROCOPTODON": { base: 1000, variants: { "R": 1200 }, img: "Procoptodon.png" },
                    "PTERANODON": { base: 600, img: "Pteranodon.png" },
                    "PULMONOSCORPIUS": { base: 1000, variants: { "ABERRANT": 1200 }, img: "Scorpion.png" },
                    "PURLOVIA": { base: 1200, variants: { "ABERRANT": 1400 }, img: "Purlovia.png" },
                    "PYROMANE": { variants: { "(DLC)": 5000 }, img: "Pyromane.png" },
                    "QUEEN BEE": { variants: { "S": 1000 }, img: "Giant_Bee.png" },
                    "QUETZAL": { base: 3000, variants: { "R": 3400, "TEK": 3400 }, img: "Quetzal.png" },
                    "RAPTOR": { base: 1200, variants: { "ABERRANT": 1300, "TEK": 1400, "X": 1300 }, img: "Raptor.png" },
                    "RAVAGER": { base: 1300, img: "Ravager.png" },
                    "REAPER": { base: 6000, variants: { "R": 7000 }, img: "Reaper.png" },
                    "REAPER KING": { variants: { "S": 7000 }, img: "Reaper.png" },
                    "REX": { base: 2500, variants: { "S": 3500, "TEK": 3000, "X": 3000 }, img: "Rex.png" },
                    "RHYNIOGNATHA": { base: 7000, variants: { "S": 9000 } },
                    "ROCK DRAKE": { base: 2400, variants: { "S": 3400 }, img: "Rock_Drake.webp" },
                    "ROLL RAT": { base: 1300, img: "Roll_Rat.png" },
                    "SABERTOOTH": { base: 1200, variants: { "X": 1400 }, img: "Sabertooth.png" },
                    "SARCO": { base: 1500, variants: { "ABERRANT": 1700 }, img: "Sarco.png" },
                    "SHADOWMANE": { base: 3600, img: "Shadowmane.png" },
                    "SHASTASAURUS": { base: 5000, img: "Shastasaurus.png" },
                    "SHINEHORN": { base: 700, variants: { "S": 1400 }, img: "Shinehorn.png" },
                    "SINOMACROPS": { base: 700, img: "Sinomacrops.png" },
                    "SNOW OWL": { base: 1100, variants: { "R": 1200, "S": 2100 }, img: "Snow_Owl.png" },
                    "SOLWYN": { variants: { "(DLC)": 2300 }, img: "Solwyn.avif" },
                    "SPINOSAURUS": { base: 1900, variants: { "ABERRANT": 2100, "S": 2400, "X": 2100 }, img: "Spino.png" },
                    "STEGOSAURUS": { base: 1300, variants: { "ABERRANT": 1500, "TEK": 1500 }, img: "Stegosaurus.png" },
                    "TAPEJARA": { base: 1000, variants: { "X": 1200 }, img: "Tapejara.png" },
                    "TERROR BIRD": { base: 1100, img: "Terror_Bird.png" },
                    "THERIZINOSAUR": { base: 1300, variants: { "S": 1800 }, img: "Therizinosaur.webp" },
                    "THORNY DRAGON": { base: 1400, img: "Thorny_Dragon.png" },
                    "THRALL": { variants: { "(DLC)": 1300 } },
                    "THYLACOLEO": { base: 2500, variants: { "R": 2700, "S": 3500 }, img: "Thylacoleo.webp" },
                    "TIDEPUP": { variants: { "(DLC)": 1500 }, img: "Empty_tidepup.png" },
                    "TITANOBOA": { base: 1600, variants: { "ABERRANT": 1800 }, img: "Titanoboa.png" },
                    "TRICERATOPS": { base: 1100, variants: { "ABERRANT": 1200, "S": 1600, "TEK": 1300, "X": 1300 }, img: "Trike.png" },
                    "TROODON": { base: 1500, img: "Troodon.png" },
                    "TROPEOGNATHUS": { base: 3100, img: "Tropeognathus.png" },
                    "TUSOTEUTHIS": { base: 3500, img: "Tusoteuthis.webp" },
                    "UMBRA": { variants: { "(DLC)": 7000 }, img: "Empty_Umbra_Icon.png" },
                    "UNICORN": { base: 2200, variants: { "S": 2700 } },
                    "VEILWYN": { variants: { "(DLC)": 1800 }, img: "VEILWYN.avif" },
                    "VELONASAUR": { base: 1300, variants: { "R": 1500, "S": 2300 }, img: "Velonasaur.webp" },
                    "VOIDWYRM": { base: 5000, img: "Voidwyrm.png" },
                    "VULTURE": { base: 800, img: "Vulture.png" },
                    "WOOLLY RHINO": { base: 1300, variants: { "X": 1500 }, img: "Woolly_Rhinoceros.png" },
                    "WYVERN": { variants: { "CRYSTAL BLOOD": 2000, "CRYSTAL EMBER": 2000, "CRYSTAL TROPICAL": 2000, "FIRE": 3000, "ICE": 3000, "LIGHTNING": 3000, "POISON": 3000, "S-FIRE": 4000, "S-ICE": 4000, "S-LIGHTNING": 4000, "S-POISON": 4000, "ZOMBIE FIRE": 4000, "ZOMBIE LIGHTNING": 4000, "ZOMBIE POISON": 4000 }, img: "Wyvern.png" },
                    "XIPHACTINUS": { base: 2000, variants: { "X": 2300 }, img: "Xiphactinus.png" },
                    "YI LING": { base: 2500, img: "YiLing.avif" },
                    "YUTYRANNUS": { base: 2400, variants: { "S": 2900, "X": 2600 }, img: "Yuthyrannus.avif" }
};



