const ICON_DATA = [
    "Achatina.png",
    "Allosaurus.png",
    "Amargasaurus.png",
	"Acrocanthosaurus.webp",
    "Ammonite.png",
    "Andrewsarchus.png",
    "Anglerfish.png",
    "Ankylosaurus.png",
    "Archaeopteryx.webp",
    "Archelon.avif",
    "Argentavis.png",
    "Arthropluera.png",
    "Astrocetus.png",
    "Astrodelphis.png",
    "Baryonyx.webp",
    "Basilisk.png",
    "Basilosaurus.png",
    "Beelzebufo.png",
    "Bison.webp",
    "Bloodstalker.png",
    "Brontosaurus.png",
    "Bulbdog.png",
    "Carbonemys.webp",
    "Carcharodontosaurus.png",
    "Carnotaurus.png",
    "Cat.webp",
    "Ceratosaurus.png",
    "Chalicotherium.png",
    "Cnidaria.png",
    "Compy.png",
    "DAEDON.png",
    "Deathworm.png",
    "Deinonychus.png",
    "Deinosuchus.png",
    "Deinotherium.avif",
    "Desmodus.png",
    "Dilophosaur.png",
    "Dimetrodon.png",
    "Dimorphodon.png",
    "Dinopithecus.png",
    "Diplocaulus.png",
    "Diplodocus.png",
    "Direwolf.png",
    "Dire_Bear.webp",
    "Dodo.png",
    "Doedicurus.png",
    "Drakeling.avif",
    "Dreadmare_Icon.avif",
    "Dreadnoughtus_Icon.avif",
    "Dung_Beetle.webp",
    "Dunkleosteus.png",
    "Electrophorus.png",
    "Equus.png",
    "Eurypterid.png",
    "Fasolasuchus.png",
    "FasolasuchusHead_Icon.avif",
    "Featherlight.png",
    "Fenrir.png",
    "Ferox.png",
    "Ferox_(Large).png",
    "Fjordhawk.png",
    "Gacha.png",
    "Gallimimus.png",
    "Gasbags.png",
    "Giant_Beaver.png",
    "Giant_Bee.png",
    "Giganotosaurus.png",
    "Gigantopithecus.png",
    "Gigantoraptor.png",
    "Glowbug.png",
    "Glowtail.png",
    "Griffin.webp",
    "Hesperornis.png",
    "Hyaenodon.png",
    "Ichthyornis.png",
    "Ichthyosaurus.png",
    "Iguanodon.png",
    "Jerboa.png",
    "Jug_Bug.png",
    "Kairuku.png",
    "Kaprosuchus.png",
    "Karkinos.png",
    "Kentrosaurus.png",
    "Lamprey.png",
    "Leedsichthys.png",
    "Liopleurodon.png",
    "Lymantria.png",
    "Lystrosaurus.png",
    "Maewing.png",
    "Magmasaur.png",
    "Mammoth.png",
    "Managarmr.webp",
    "Manta.png",
    "Mantis.png",
    "Megachelon.png",
    "Megalania.webp",
    "Megaloceros.png",
    "Megalodon.png",
    "Megalosaurus.png",
    "Meganeura.png",
    "Megatherium.png",
	"Megaraptor.avif",
    "Mesopithecus.png",
    "Microraptor.png",
    "Morellatops.png",
    "Mosasaurus.png",
    "Moschops.png",
    "Nameless.png",
    "Noglin.png",
    "Oasisaur.png",
    "Onyc.png",
    "ossidon.avif",
    "Otter.png",
    "Oviraptor.png",
    "Ovis.png",
    "Pachy.png",
    "Pachyrhinosaurus.png",
    "Paraceratherium.webp",
    "Parasaur.png",
    "Pegomastax.png",
    "Pelagornis.png",
    "Phiomia.webp",
    "Phoenix.png",
    "Plesiosaur.png",
    "Procoptodon.png",
    "Pteranodon.png",
    "Purlovia.png",
    "Pyromane.png",
    "Quetzal.png",
    "Raptor.png",
    "Ravager.png",
    "Reaper.png",
    "Rex.png",
    "Rock_Drake.webp",
    "Rock_Elemental.png",
    "Roll_Rat.png",
    "Sabertooth.png",
    "Sarco.png",
    "Scorpion.png",
    "Shadowmane.png",
    "Shastasaurus.png",
    "Shinehorn.png",
    "Sinomacrops.png",
    "Snow_Owl.png",
    "Spider.png",
    "Spino.png",
    "Stegosaurus.png",
    "Tapejara.png",
    "Tek_Stryder.png",
    "Terror_Bird.png",
    "Therizinosaur.webp",
    "Thorny_Dragon.png",
    "Thylacoleo.webp",
    "Titanoboa.png",
    "Titanosaur.png",
    "Trike.png",
    "Trilobite.png",
    "Troodon.png",
    "Tropeognathus.png",
    "Tusoteuthis.webp",
    "VEILWYN.avif",
    "Velonasaur.webp",
    "Voidwyrm.png",
    "Vulture.png",
    "Woolly_Rhinoceros.png",
    "Wyvern.png",
    "Xiphactinus.png",
    "YiLing.avif",
    "Yuthyrannus.avif",
    "malwyn.avif",
    "ossidon.avif",
    "Solwyn.avif"
];
const DINO_REGISTRY = {
                    "ACHATINA": { base: 500, variants: { "ABERRANT": 700 } },
					"ACROCANTHOSAURUS" { base: 2800, variants: { "S (MOD)": 3800 }, img: "Acrocanthosaurus.webp" },
                    "ALLOSAURUS": { base: 1800, variants: { "R": 2000, "S (MOD)": 2300, "X": 2000 } },
                    "AMARGASAURUS": { base: 3000 },
                    "ANDREWSARCHUS": { base: 1800, variants: { "S (MOD)": 2800 } },
                    "ANGLERFISH": { base: 1100, variants: { "ABERRANT": 1300 } },
                    "ANKYLOSAURUS": { base: 500, variants: { "ABERRANT": 700, "S (MOD)": 1000, "X": 700 } },
                    "ARANEO": { base: 600, variants: { "ABERRANT": 800 }, img: "Spider.png" },
                    "ARCHAEOPTERYX": { base: 900 },
                    "ARCHELON": { base: 1800, img: "Archelon.avif" },
                    "ARGENTAVIS": { base: 600, variants: { "X": 800 } },
                    "ARMADOGGO": { base: 1700 },
                    "ARTHROPLUERA": { base: 1300, variants: { "ABERRANT": 1500 } },
                    "ASTROCETUS": { base: 25000 },
                    "ASTRODELPHIS": { base: 19000 },
                    "AURELIAX": { base: 4000 },
                    "BARYONYX": { base: 1100, variants: { "ABERRANT": 1300 } },
                    "BASILISK": { base: 3000 },
                    "BASILOSAURUS": { base: 2500, variants: { "S (MOD)": 3000, "X": 2700 } },
                    "BEELZEBUFO": { base: 800, variants: { "ABERRANT": 1000 } },
                    "BISON": { base: 2200, img: "Bison.webp" },
                    "BLOODSTALKER": { base: 2100 },
                    "BRONTOSAURUS": { base: 2300, variants: { "R": 2500 } },
                    "BULBDOG": { base: 600 },
                    "CARBONEMYS": { base: 500, variants: { "ABERRANT": 600, "R": 600 } },
                    "CARCHARODONTOSAURUS": { base: 5000, variants: { "S (MOD)": 6000 } },
                    "CARNOTAURUS": { base: 1600, variants: { "ABERRANT": 1800 } },
                    "CASTROIDES": { base: 600, img: "Giant_Beaver.png" },
                    "CAT": { base: 800, variants: { "S (MOD)": 1300 }, img: "Cat.webp" },
                    "CERATOSAURUS": { base: 2000, variants: { "S (MOD)": 3000 } },
                    "CHALICOTHERIUM": { base: 1500 },
                    "COMPY": { base: 500 },
                    "COSMO": { base: 1200 },
                    "CRYOLOPHOSAURUS": { base: 2700 },
                    "DAEDON": { base: 1700, variants: { "R": 1900, "S (MOD)": 3700 }, img: "DAEDON.png" },
                    "DEINONYCHUS": { base: 2000, variants: { "S (MOD)": 3000 } },
                    "DEINOSUCHUS": { base: 2200, variants: { "S (MOD)": 3200 } },
                    "DEINOTHERIUM": { base: 2800 },
                    "DESMODUS": { base: 1600, variants: { "S (MOD)": 2600 } },
                    "DILOPHOSAUR": { base: 500, variants: { "R": 700 } },
                    "DIMETRODON": { base: 1000, variants: { "ABERRANT": 1200 } },
                    "DIMORPHODON": { base: 500, variants: { "ABERRANT": 700 } },
                    "DINOPITHECUS": { base: 1500 },
                    "DIPLOCAULUS": { base: 900, variants: { "ABERRANT": 1100 } },
                    "DIPLODOCUS": { base: 1800, variants: { "ABERRANT": 2000 } },
                    "DIRE BEAR": { base: 1000, variants: { "ABERRANT": 1200, "S (MOD)": 1500 } },
                    "DIREWOLF": { base: 1100, variants: { "R": 1300, "S (MOD)": 2100 } },
                    "DODO": { base: 200, variants: { "ABERRANT": 400, "ZOMBIE": 500 } },
                    "DOEDICURUS": { base: 500, variants: { "ABERRANT": 700, "S (MOD)": 1000 } },
                    "DRAKELING": { base: 2000, img: "Drakeling.avif" },
                    "DREADMARE": { base: 10000, img: "Dreadmare_Icon.avif" },
                    "DREADNOUGHTUS": { base: 6500, img: "Dreadnoughtus_Icon.avif" },
                    "DUNG BEETLE": { base: 300, variants: { "ABERRANT": 500 } },
                    "DUNKLEOSTEUS": { base: 2000, variants: { "S (MOD)": 3000, "X": 2200 } },
                    "ELDERCLAW": { base: 10000 },
                    "ELECTROPHORUS": { base: 1500, variants: { "ABERRANT": 1700 } },
                    "ENFORCER": { base: 3000 },
                    "EQUUS": { base: 1200, variants: { "ABERRANT": 1400, "R": 1400 } },
                    "FASOLOZUCHUS": { base: 4000, variants: { "ABERRANT": 5000, "S (MOD)": 8000 }, img: "Fasolasuchus.png" },
                    "FEATHERLIGHT": { base: 700 },
                    "FENRIR": { base: 3500, variants: { "S (MOD)": 1800 } },
                    "FEROX": { base: 1900 },
                    "FJORDHAWK": { base: 1100 },
                    "GACHA": { base: 1000 },
                    "GALLIMIMUS": { base: 1000 },
                    "GASBAG": { base: 1300, variants: { "R": 1500 }, img: "Gasbags.png" },
                    "GIANT BEE": { base: 500 },
                    "GIGADESMODUS": { base: 7000 },
                    "GIGANOTOSAURUS": { base: 4000, variants: { "R": 4500, "TEK": 6000 } },
                    "GIGANTOPITHECUS": { base: 1200, variants: { "ABERRANT": 1400 } },
                    "GIGANOTORAPTOR": { base: 5000, variants: { "ABERRANT": 6000 }, img: "Gigantoraptor.png" },
                    "GLOON": { base: 2000 },
                    "GLOWTAIL": { base: 600 },
                    "GOLEM": { base: 2500, variants: { "CHALK": 3000, "ICE": 3000, "LAVA": 3000, "ROCK": 2500 } },
                    "GRIFFIN": { base: 1900, variants: { "S (MOD)": 2900 } },
                    "HELICOPRION": { base: 3000 },
                    "HESPERONIS": { base: 2000, img: "Hesperornis.png" },
                    "HYAENODON": { base: 1400 },
                    "ICHTHYORNIS": { base: 800 },
                    "ICHTHYOSAURUS": { base: 1100, variants: { "X": 1300 } },
                    "IGUANODON": { base: 1200, variants: { "ABERRANT": 1400 } },
                    "JERBOA": { base: 500 },
                    "KAIRUKU": { base: 900 },
                    "KAPROSUCHUS": { base: 1300 },
                    "KARKINOS": { base: 4200 },
                    "KENTROSAURUS": { base: 1200 },
                    "LIOPLEURODON": { base: 2000 },
                    "LYMANTRIA": { base: 1000 },
                    "LYSTROSAURUS": { base: 700, variants: { "ABERRANT": 900 } },
                    "MAEGUANA": { base: 900, variants: { "S (MOD)": 1400 } },
                    "MAEWING": { base: 900, variants: { "S (MOD)": 1400 }, img: "Maewing.png" },
                    "MAGMASAUR": { base: 3400 },
                    "MALWYN": { base: 2500, img: "malwyn.avif" },
                    "MAMMOTH": { base: 1200 },
                    "MANAGARMR": { base: 3300, variants: { "S (MOD)": 4300 } },
                    "MANTA": { base: 1400, variants: { "ABERRANT": 1600 } },
                    "MANTIS": { base: 1900, variants: { "S (MOD)": 2900 } },
                    "MEGACHELON": { base: 6000 },
                    "MEGALANIA": { base: 1100, variants: { "ABERRANT": 1400 } },
                    "MEGALOCEROS": { base: 1300 },
                    "MEGALODON": { base: 1700, variants: { "S (MOD)": 2700, "X": 1800 } },
                    "MEGALOSAURUS": { base: 2000, variants: { "ABERRANT": 2200, "S (MOD)": 4000 } },
                    "MEGARAPTOR": { base: 2700, variants: { "S (MOD)": 4700 } },
                    "MEGATHERIUM": { base: 1800, variants: { "R": 2000 } },
                    "MESOPITEKUS": { base: 700, img: "Mesopithecus.png" },
                    "MICRORAPTOR": { base: 800 },
                    "MORELLATOPS": { base: 1100 },
                    "MOSA": { base: 3700, variants: { "S (MOD)": 4200, "X": 3900 }, img: "Mosasaurus.png" },
                    "MOSCHOPS": { base: 400, variants: { "ABERRANT": 600 } },
                    "NOGLIN": { base: 8000 },
                    "ONYC": { base: 1500 },
                    "OSSIDON": { base: 3000, variants: { "S (MOD)": 5000 }, img: "ossidon.avif" },
                    "OTTER": { base: 700, variants: { "ABERRANT": 900, "S (MOD)": 1200, "X": 900 } },
                    "OVIRAPTOR": { base: 500 },
                    "OVIS": { base: 600, variants: { "ABERRANT": 800 } },
                    "PACHYRHINOSARURUS": { base: 1300 },
                    "PARACERATHERIUM": { base: 1300, variants: { "ABERRANT": 1500, "X": 1500 } },
                    "PARASAUR": { base: 1000, variants: { "ABERRANT": 1200, "R": 1200, "TEK": 1200, "X": 1200 } },
                    "PEGOMASTAX": { base: 900 },
                    "PELARGONIS": { base: 900, img: "Pelagornis.png" },
                    "PHIOMIA": { base: 700 },
                    "PHOENIX": { base: 9000 },
                    "PLESIOSAUR": { base: 3700, variants: { "S (MOD)": 4200 } },
                    "PROCOPTODON": { base: 1000, variants: { "R": 1200 } },
                    "PTERANADON": { base: 600 },
                    "PULMONOSCORPIUS": { base: 1000, variants: { "ABERRANT": 1200 }, img: "Scorpion.png" },
                    "PURLOVIA": { base: 1200, variants: { "ABERRANT": 1400 } },
                    "PYROMANE": { base: 7500 },
                    "QUEEN BEE": { variants: { "S (MOD)": 1000 } },
                    "QUETZAL": { base: 3000, variants: { "R": 3400, "TEK": 3400 } },
                    "RAPTOR": { base: 1200, variants: { "ABERRANT": 1300, "TEK": 1400 } },
                    "RAVAGER": { base: 1300 },
                    "REAPER": { base: 6000, variants: { "R": 7000 } },
                    "REAPER KING": { variants: { "S (MOD)": 7000 } },
                    "REX": { base: 2500, variants: { "S (MOD)": 3500, "TEK": 3000, "X": 3000 } },
                    "RHYNIOGNATHA": { base: 7000, variants: { "S (MOD)": 9000 } },
                    "ROCK DRAKE": { base: 2400, variants: { "S (MOD)": 3400 } },
                    "ROLL RAT": { base: 1300 },
                    "SABERTOOTH": { base: 1200, variants: { "X": 1400 } },
                    "SARCO": { base: 1500, variants: { "ABERRANT": 1700 } },
                    "SHADOWMANE": { base: 3600 },
                    "SHASTASAURUS": { base: 5000 },
                    "SHINEHORN": { base: 700, variants: { "S (MOD)": 1400 } },
                    "SINOMACROPS": { base: 700 },
                    "SNOW OWL": { base: 1100, variants: { "R": 1200, "S (MOD)": 2100 } },
                    "SOLWYN": { base: 2300, img: "Solwyn.avif" },
                    "SPINOSAURUS": { base: 1900, variants: { "ABERRANT": 2100, "S (MOD)": 2400, "X": 2100 } },
                    "STEGOSAURUS": { base: 1300, variants: { "ABERRANT": 1500, "TEK": 1500 } },
                    "TAPEJARA": { base: 1000, variants: { "X": 1200 } },
                    "TERROR BIRD": { base: 1100 },
                    "THERIZINO": { base: 1300, variants: { "S (MOD)": 1800 }, img: "Therizinosaur.webp" },
                    "THORNY DRAGON": { base: 1400 },
                    "THRALL": { base: 1300 },
                    "THYLACOLEO": { base: 2500, variants: { "R": 2700, "S (MOD)": 3500 } },
                    "TITANOBOA": { base: 1600, variants: { "ABERRANT": 1800 } },
                    "TRICERATOPS": { base: 1100, variants: { "ABERRANT": 1200, "S (MOD)": 1600, "TEK": 1300, "X": 1300 } },
                    "TROODON": { base: 1500 },
                    "TROPEOGNATHUS": { base: 3100 },
                    "TUSO": { base: 3500, img: "Tusoteuthis.webp" },
                    "UNICORN": { base: 2200, variants: { "S (MOD)": 2700 } },
                    "VEILWYN": { base: 1800, img: "VEILWYN.avif" },
                    "VELONASAUR": { base: 1300, variants: { "R": 1500, "S (MOD)": 2300 } },
                    "VOIDWYRM": { base: 5000 },
                    "VULTURE": { base: 800 },
                    "WOOLLY RHINO": { base: 1300, variants: { "X": 1500 } },
                    "WYVERN": {
                        base: 3000,
                        variants: {
                            "CRYSTAL BLOOD": 2000, "CRYSTAL EMBER": 2000, "CRYSTAL TROPICAL": 2000,
                            "FIRE": 8200, "ICE": 8200, "LIGHTNING": 8050, "POISON": 8050,
                            "FIRE-S": 4000, "ICE-S": 4000, "LIGHTNING-S": 4000, "POISON-S": 4000,
                            "S-FIRE": 4000, "S-ICE": 4000, "S-LIGHTNING": 4000, "S-POISON": 4000,
                            "ZOMBIE FIRE": 8200, "ZOMBIE LIGHTNING": 8050, "ZOMBIE POISON": 8050
                        }
                    },
                    "XIPHACTINUS": { base: 2000 },
                    "YI LING": { base: 2500, img: "YiLing.avif" },
                    "YUTHYRANNUS": { base: 2400, variants: { "X": 2600 }, img: "Yuthyrannus.avif" }
                };
